version: '3.8'

services:
    mongodb:
        image: mongo:latest
        container_name: workoutdb
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
            MONGO_INITDB_DATABASE: workoutdb
        volumes:
            - mongodb_data:/data/db

volumes:
    mongodb_data:

