package io.github.nfers.ms_workout.domain.model

import lombok.Data;

@Data
public class ExerciseExecution {

    private String id;
    private String name;
    private String description;
    private String videoUrl;
    private String thumbnailUrl;
    private Duration duration;
    private int repetitions;
    private int sets;
    private int restTime;
    private int difficultyLevel;

    // Constructors, getters, and setters can be generated by Lombok
}
