package io.github.nfers.ms_workout.domain.model;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.RequiredArgsConstructor;

@Getter
public enum MuscleGroup {
    CHEST("Chest"),
    BACK("Back"),
    LEGS("Legs"),
    SHOULDERS("Shoulders"),
    ARMS("Arms"),
    CORE("Core"),
    GLUTES("Glutes"),
    CALVES("Calves"),
    FULL_BODY("Full Body"),
    CARDIO("Cardio"),
    STRETCHING("Stretching"),
    YOGA("Yoga"),
    PILATES("Pilates"),
    DANCE("Dance"),
    HIIT("HIIT"),
    FUNCTIONAL("Functional"),
    MOBILITY("Mobility"),
    BALANCE("Balance"),
    STRENGTH("Strength"),
    ENDURANCE("Endurance"),
    FLEXIBILITY("Flexibility"),
    AGILITY("Agility"),
    COORDINATION("Coordination"),
    SPEED("Speed"),
    POWER("Power"),
    STAMINA("Stamina"),
    RECOVERY("Recovery"),
    PREHAB("Prehab"),
    REHAB("Rehab"),
    CONDITIONING("Conditioning"),
    WARMUP("Warm-up"),
    COOL_DOWN("Cool Down"),
    STRETCH("Stretch"),
    CARDIOVASCULAR("Cardiovascular"),
    RESISTANCE("Resistance"),
    BODYWEIGHT("Bodyweight"),
    FUNCTIONAL_TRAINING("Functional Training"),
    CIRCUIT_TRAINING("Circuit Training"),
    HIGH_INTENSITY("High Intensity"),
    LOW_INTENSITY("Low Intensity"),
    ENDURANCE_TRAINING("Endurance Training"),
    STRENGTH_TRAINING("Strength Training"),
    POWERLIFTING("Powerlifting"),
    BODYBUILDING("Bodybuilding"),
    CROSSFIT("CrossFit"),
    CALISTHENICS("Calisthenics"),
    PILATES_REFORMER("Pilates Reformer"),
    BARRE("Barre"),
    AQUATIC("Aquatic"),
    MARTIAL_ARTS("Martial Arts"),
    BOXING("Boxing"),
    KICKBOXING("Kickboxing"),
    TAI_CHI("Tai Chi"),
    QIGONG("Qigong"),
    ZUMBA("Zumba"),
    AEROBICS("Aerobics"),
    SPINNING("Spinning"),
    STEP_AEROBICS("Step Aerobics"),
    OTH
}
